import axios from 'axios';

const api = axios.create({ baseURL: '/api/v2', withCredentials: true });
let refreshPromise;
api.interceptors.response.use((response) => response, async (error) => {
  const original = error.config;
  const authMutation = ['/auth/login', '/auth/signup', '/auth/logout', '/auth/refresh'].includes(original?.url);
  if (error.response?.status !== 401 || original?._retried || authMutation) throw error;
  original._retried = true;
  try { refreshPromise ||= api.post('/auth/refresh').finally(() => { refreshPromise = null; }); await refreshPromise; return api(original); } catch { throw error; }
});
async function request(method, url, data, config) {
  try { return (await api({ method, url, data, ...config })).data; } catch (error) { const detail = error.response?.data?.error; throw Object.assign(new Error(detail?.message || 'Request failed.'), { status: error.response?.status, code: detail?.code }); }
}
export const authApi = { me: () => request('get', '/me'), login: (data) => request('post', '/auth/login', data), signup: (data) => request('post', '/auth/signup', data), logout: () => request('post', '/auth/logout') };
export const libraryApi = { mine: (page = 1, pageSize = 60) => request('get', `/me/library?page=${page}&pageSize=${pageSize}`), users: () => request('get', '/users'), compare: (userIds) => request('post', '/library-comparisons', { userIds }), addManualGame: (gameId) => request('put', `/me/library/games/${encodeURIComponent(gameId)}`), removeManualGame: (gameId) => request('delete', `/me/library/games/${encodeURIComponent(gameId)}`, { confirmation: 'REMOVE FROM LIBRARY' }), linkSteam: (steamId) => request('put', '/me/providers/steam', { steamId }), syncSteam: () => request('post', '/me/providers/steam/sync', {}), job: (jobId) => request('get', `/me/imports/${jobId}`), upload: (provider, file) => { const data = new FormData(); data.append('provider', provider); data.append('file', file); return request('post', '/me/imports', data); } };
const catalogueQuery = ({ query = '', page = 1, pageSize = 24, sort = 'rating', genres = [], platforms = [], gameModes = [] } = {}) => {
  const params = new URLSearchParams({ page: String(page), pageSize: String(pageSize), sort });
  if (query.trim()) params.set('q', query.trim());
  genres.forEach((genre) => params.append('genre', genre)); platforms.forEach((platform) => params.append('platform', platform)); gameModes.forEach((mode) => params.append('gameMode', mode));
  return params.toString();
};
export const catalogueApi = { games: (options = {}) => request('get', `/games?${catalogueQuery(options)}`), game: (gameId) => request('get', `/games/${encodeURIComponent(gameId)}`), owners: (gameId) => request('get', `/games/${encodeURIComponent(gameId)}/owners`), filters: () => request('get', '/game-filters') };
export const communityApi = { topGames: () => request('get', '/community/games/top?limit=20') };
export const retroApi = { link: (username) => request('put', '/me/retroachievements', { username }), profile: () => request('get', '/me/retroachievements/profile'), challenge: () => request('get', '/retroachievements/challenge') };
export const adminApi = { jobs: () => request('get', '/admin/jobs'), enrichmentStatus: () => request('get', '/admin/enrichment-status'), repairEnrichment: () => request('post', '/admin/enrichment-repair'), recoverEnrichment: () => request('post', '/admin/enrichment-repair'), refreshAllMetadata: () => request('post', '/admin/enrichment-refresh-all', { confirmation: 'REFRESH ALL IGDB METADATA' }), refreshGameMetadata: (gameId) => request('post', `/admin/games/${gameId}/metadata-refresh`), resetEnrichment: () => request('post', '/admin/enrichment-reset', { confirmation: 'RESET IGDB' }), reviews: () => request('get', '/admin/matches/review'), metadataReviews: (page = 1, pageSize = 30) => request('get', `/admin/metadata-reviews?page=${page}&pageSize=${pageSize}`), games: (query, page = 1, pageSize = 12) => request('get', `/admin/games?page=${page}&pageSize=${pageSize}${query ? `&q=${encodeURIComponent(query)}` : ''}`), igdbSearch: (query) => request('get', `/admin/igdb-search?q=${encodeURIComponent(query)}`), assignIgdb: (gameId, igdbId) => request('put', `/admin/games/${gameId}/igdb`, { igdbId }), assignIgdbUrl: (gameId, url) => request('put', `/admin/games/${gameId}/igdb-url`, { url }), manualMetadata: (gameId, data) => request('put', `/admin/games/${gameId}/manual-metadata`, data), setVisibility: (gameId, hidden) => request('put', `/admin/games/${gameId}/visibility`, { hidden }), createGame: (data) => request('post', '/admin/games', data), createFromIgdbUrl: (url) => request('post', '/admin/games/from-igdb-url', { url }), updateGame: (gameId, data) => request('put', `/admin/games/${gameId}`, data), mergeGames: (sourceGameId, targetGameId, reason) => request('post', `/admin/games/${sourceGameId}/merge`, { targetGameId, reason }), archiveGame: (gameId, reason) => request('delete', `/admin/games/${gameId}`, { reason }), resolveMatch: (matchId, canonicalGameId) => request('put', `/admin/matches/${matchId}`, { canonicalGameId }), activateRetroChallenge: (retroGameId, description) => request('put', '/admin/retroachievements/challenge', { retroGameId: Number(retroGameId), description }) };