const express = require('express'); const mongoose = require('mongoose'); const { requireAuth, requireRole } = require('../http/auth'); const { AppError } = require('../http/errors'); const { exactKeys, object, string } = require('../http/validate'); const Playlist = require('../models/CasualFridayPlaylist'); const { buildPlaylistDto, createPlaylist, createRotation, listRotation, publishPlaylist, retireRotation, setEntries, updateRotation } = require('../services/casualFridayService');
const roles = ['helper', 'admin']; const objectId = (value, field) => { if (!mongoose.isObjectIdOrHexString(value)) throw new AppError(400, 'invalid_request', `${field} must be valid`); return value; }; const integer = (value, field) => { if (!Number.isInteger(value)) throw new AppError(400, 'invalid_request', `${field} must be an integer`); return value; };
function rotationBody(body, includeGame = false) { object(body); exactKeys(body, [...(includeGame ? ['canonicalGameId'] : []), 'playerCountMin', 'playerCountMax', 'playerCountLabel', 'joinInstructions', 'hostMode', 'availabilityOverride', 'acquisitionUrlOverride', 'availabilityNote']); const result = { ...body, playerCountMin: integer(body.playerCountMin, 'playerCountMin'), playerCountMax: integer(body.playerCountMax, 'playerCountMax') }; if (includeGame) result.canonicalGameId = objectId(body.canonicalGameId, 'canonicalGameId'); if (result.playerCountMin < 1 || result.playerCountMax < result.playerCountMin || !['none', 'host_runs', 'streamable'].includes(result.hostMode) || !['none', 'free'].includes(result.availabilityOverride)) throw new AppError(400, 'invalid_request', 'Rotation fields are invalid'); if (result.availabilityOverride === 'free' && (typeof result.acquisitionUrlOverride !== 'string' || !/^https:\/\//.test(result.acquisitionUrlOverride))) throw new AppError(400, 'invalid_request', 'Free games need an HTTPS acquisition URL'); return result; }
function createCasualFridayRouter(config) { const router = express.Router(); const manage = [requireAuth(config), requireRole(...roles)];
  router.get('/casual-friday', requireAuth(config), async (req, res, next) => { try { const playlist = await Playlist.findOne({ status: 'published', startsAt: { $lte: new Date() }, endsAt: { $gt: new Date() } }).sort({ startsAt: 1 }); res.json({ playlist: await buildPlaylistDto(playlist, req.user._id) }); } catch (error) { next(error); } });
  router.get('/casual-friday/rotation', requireAuth(config), async (req, res, next) => { try { res.json({ rotation: (await listRotation()).filter((item) => item.status === 'active') }); } catch (error) { next(error); } });
  router.get('/casual-friday/manage/rotation', ...manage, async (req, res, next) => { try { res.json({ rotation: await listRotation() }); } catch (error) { next(error); } });
  router.post('/casual-friday/manage/rotation', ...manage, async (req, res, next) => { try { res.status(201).json({ rotation: await createRotation(req.user, rotationBody(req.body, true)) }); } catch (error) { next(error); } });
  router.put('/casual-friday/manage/rotation/:id', ...manage, async (req, res, next) => { try { res.json({ rotation: await updateRotation(req.user, objectId(req.params.id, 'id'), rotationBody(req.body)) }); } catch (error) { next(error); } });
  router.post('/casual-friday/manage/rotation/:id/retire', ...manage, async (req, res, next) => { try { const body = object(req.body); exactKeys(body, ['reason']); await retireRotation(req.user, objectId(req.params.id, 'id'), string(body.reason, 'reason', { max: 1000 })); res.status(204).end(); } catch (error) { next(error); } });
  router.post('/casual-friday/manage/playlists', ...manage, async (req, res, next) => { try { const body = object(req.body); exactKeys(body, ['weekKey', 'startsAt', 'endsAt', 'notes']); const playlist = await createPlaylist(req.user, { weekKey: string(body.weekKey, 'weekKey', { min: 10, max: 10 }), startsAt: new Date(body.startsAt), endsAt: new Date(body.endsAt), notes: typeof body.notes === 'string' ? body.notes.trim() : undefined }); res.status(201).json({ playlist }); } catch (error) { next(error); } });
  router.get('/casual-friday/manage/playlists/current', ...manage, async (req, res, next) => { try { const playlist = await Playlist.findOne({ status: { $in: ['draft', 'published'] } }).sort({ startsAt: 1 }); res.json({ playlist: await buildPlaylistDto(playlist) }); } catch (error) { next(error); } });
  router.put('/casual-friday/manage/playlists/:id/entries', ...manage, async (req, res, next) => { try { const body = object(req.body); exactKeys(body, ['version', 'rotationGameIds']); res.json({ playlist: await setEntries(req.user, objectId(req.params.id, 'id'), integer(body.version, 'version'), body.rotationGameIds) }); } catch (error) { next(error); } });
  router.post('/casual-friday/manage/playlists/:id/publish', ...manage, async (req, res, next) => { try { const body = object(req.body); exactKeys(body, ['version']); res.json({ playlist: await publishPlaylist(req.user, objectId(req.params.id, 'id'), integer(body.version, 'version')) }); } catch (error) { next(error); } });
  return router;
}
module.exports = { createCasualFridayRouter };