import { lazy, Suspense, useState } from 'react';
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation } from 'react-router-dom';
import { Alert, AppBar, Box, Button, Card, CardContent, Chip, CircularProgress, Container, Divider, Drawer, Grid, IconButton, List, ListItemButton, ListItemText, MenuItem, Stack, TextField, Toolbar, Typography } from '@mui/material';
import MenuIcon from '@mui/icons-material/Menu';
import GamepadIcon from '@mui/icons-material/Gamepad';
import { adminApi, catalogueApi, retroApi } from './services/api';
import { useAuth } from './context/useAuth';
import { useLoad } from './hooks/useLoad';

const links = [['Home', '/'], ['Library', '/library'], ['Compare', '/compare'], ['Catalogue', '/catalogue'], ['Retro', '/retro']];
const Home = lazy(() => import('./pages/Home'));
const Library = lazy(() => import('./pages/Library'));
const Compare = lazy(() => import('./pages/Compare'));
const Catalogue = lazy(() => import('./pages/Catalogue'));
function ErrorNotice({ value }) { return value ? <Alert severity="error">{value}</Alert> : null; }
function Shell({ children }) {
  const { user, loading, logout } = useAuth(); const [drawer, setDrawer] = useState(false); const location = useLocation();
  if (loading) return <Box sx={{ minHeight: '100vh', display: 'grid', placeItems: 'center' }}><CircularProgress /></Box>;
  const navigation = <List sx={{ p: 1 }}>{links.map(([label, to]) => <ListItemButton key={to} component={Link} to={to} selected={location.pathname === to} onClick={() => setDrawer(false)}><ListItemText primary={label} /></ListItemButton>)}{user?.role === 'admin' && <ListItemButton component={Link} to="/admin" selected={location.pathname === '/admin'}><ListItemText primary="Admin" /></ListItemButton>}</List>;
  return <Box sx={{ minHeight: '100vh' }}><AppBar position="sticky" color="transparent" elevation={0} sx={{ backdropFilter: 'blur(14px)', borderBottom: 1, borderColor: 'divider' }}><Toolbar><IconButton aria-label="Open navigation" onClick={() => setDrawer(true)} sx={{ display: { md: 'none' }, mr: 1 }}><MenuIcon /></IconButton><Stack component={Link} to="/" direction="row" spacing={1} alignItems="center" sx={{ flexGrow: 1, color: 'inherit', textDecoration: 'none' }}><GamepadIcon color="primary" /><Typography className="pixel-label">GSPLAY V2</Typography></Stack>{user ? <Stack direction="row" alignItems="center" spacing={1}><Typography sx={{ display: { xs: 'none', sm: 'block' } }}>{user.username}</Typography><Button color="inherit" onClick={logout}>Log out</Button></Stack> : <Button component={Link} to="/login" variant="contained">Sign in</Button>}</Toolbar></AppBar><Drawer open={drawer} onClose={() => setDrawer(false)}><Box sx={{ pt: 8, width: 240 }}>{navigation}</Box></Drawer><Box sx={{ display: 'flex' }}><Box component="aside" sx={{ width: 220, borderRight: 1, borderColor: 'divider', display: { xs: 'none', md: 'block' }, minHeight: 'calc(100vh - 65px)' }}>{navigation}</Box><Container component="main" maxWidth="xl" sx={{ flexGrow: 1, py: { xs: 3, md: 5 } }}>{children}</Container></Box></Box>;
}
function Protected({ children }) { const { user, loading } = useAuth(); return loading ? null : user ? children : <Navigate to="/login" />; }
function AuthPage({ signup = false }) { const { user, login, signup: register } = useAuth(); const [form, setForm] = useState({ username: '', password: '' }); const [error, setError] = useState(''); if (user) return <Navigate to="/" />; const submit = async (event) => { event.preventDefault(); try { await (signup ? register : login)(form); } catch (err) { setError(err.message); } }; return <Container maxWidth="sm" sx={{ pt: 12 }}><Card><CardContent sx={{ p: 4 }}><Typography variant="h2">{signup ? 'Create account' : 'Welcome back'}</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Your games, your group, your private dashboard.</Typography><Box component="form" onSubmit={submit}><Stack spacing={2}><ErrorNotice value={error} /><TextField required label="Username" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /><TextField required type="password" label="Password" helperText="At least 8 characters" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /><Button type="submit" variant="contained" size="large">{signup ? 'Create account' : 'Sign in'}</Button><Button component={Link} to={signup ? '/login' : '/signup'}>{signup ? 'Already have an account? Sign in' : 'New here? Create an account'}</Button></Stack></Box></CardContent></Card></Container>; }
function Retro() { const { user, refresh } = useAuth(); const [username, setUsername] = useState(user?.retroachievements?.username || ''); const [version, setVersion] = useState(0); const profile = useLoad(retroApi.profile, [version]); const challenge = useLoad(retroApi.challenge, [version]); const [error, setError] = useState(''); const submit = async () => { try { await retroApi.link(username); await refresh(); setVersion((current) => current + 1); } catch (err) { setError(err.message); } }; const active = challenge.data?.challenge; return <Stack spacing={3}><Typography variant="h2">RetroAchievements</Typography><Card><CardContent><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><TextField fullWidth label="RetroAchievements username" value={username} onChange={(event) => setUsername(event.target.value)} /><Button variant="contained" onClick={submit}>Link account</Button></Stack></CardContent></Card><ErrorNotice value={error || (profile.error && !user?.retroachievements ? null : profile.error) || challenge.error} />{profile.data?.profile && <Card><CardContent><Stack direction="row" spacing={2} alignItems="center">{profile.data.profile.avatarUrl && <Box component="img" src={profile.data.profile.avatarUrl} alt="" sx={{ width: 56, height: 56, borderRadius: '50%' }} />}<Box><Typography variant="h5">{profile.data.profile.displayName}</Typography><Typography color="primary">{profile.data.profile.points ?? '—'} points</Typography></Box></Stack></CardContent></Card>}<Card><CardContent>{active ? <Stack spacing={2}><Typography className="pixel-label" color="primary">ACTIVE RETRO CHALLENGE</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}>{active.imageUrl && <Box component="img" src={active.imageUrl} alt="" sx={{ width: { xs: '100%', sm: 160 }, maxHeight: 110, objectFit: 'cover', borderRadius: 1 }} />}<Box><Typography variant="h5">{active.title}</Typography><Typography color="text.secondary">{active.consoleName}</Typography><Typography sx={{ mt: 1 }}>{active.description || 'Join the community challenge and track your progress.'}</Typography>{active.progress ? <Typography color="primary" sx={{ mt: 1 }}>{active.progress.earned}/{active.progress.total} achievements · {active.progress.points} points</Typography> : <Typography color="text.secondary" sx={{ mt: 1 }}>Link your RetroAchievements account to see personal progress.</Typography>}</Box></Stack></Stack> : <Typography color="text.secondary">No Retro challenge is active right now.</Typography>}</CardContent></Card></Stack>; }
function Admin() {
  const { user } = useAuth(); const jobs = useLoad(adminApi.jobs, []); const enrichment = useLoad(adminApi.enrichmentStatus, []); const [reviewVersion, setReviewVersion] = useState(0); const reviews = useLoad(adminApi.reviews, [reviewVersion]); const games = useLoad(() => catalogueApi.games(), []); const [selected, setSelected] = useState({}); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [retroGameId, setRetroGameId] = useState(''); const [retroDescription, setRetroDescription] = useState('');
  if (user?.role !== 'admin') return <Navigate to="/" />;
  const resolve = async (matchId) => { try { const canonicalGameId = selected[matchId]; if (!canonicalGameId) return; await adminApi.resolveMatch(matchId, canonicalGameId); setNotice('Match resolved and saved as a reusable alias.'); setSelected({}); setReviewVersion((version) => version + 1); } catch (err) { setError(err.message); } };
  const activateChallenge = async () => { try { await adminApi.activateRetroChallenge(retroGameId, retroDescription); setNotice('Retro challenge activated.'); setRetroGameId(''); setRetroDescription(''); } catch (err) { setError(err.message); } };
  const repair = async () => { try { await adminApi.repairEnrichment(); setNotice('Metadata repair has been queued.'); } catch (err) { setError(err.message); } };
  return <Stack spacing={3}><Typography variant="h2">Admin operations</Typography>{notice && <Alert severity="success">{notice}</Alert>}<ErrorNotice value={error || jobs.error || enrichment.error || reviews.error || games.error} /><Card><CardContent><Typography variant="h6">Metadata enrichment</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>{enrichment.data?.metadata?.complete || 0}/{enrichment.data?.metadata?.total || 0} complete · {enrichment.data?.metadata?.enrichedPercent || 0}%</Typography><Typography color="text.secondary">Pending {enrichment.data?.metadata?.pending || 0} · Retryable {enrichment.data?.metadata?.retryableError || 0} · Failed {enrichment.data?.metadata?.permanentError || 0}</Typography><Button variant="contained" sx={{ mt: 2 }} onClick={repair}>Repair pending enrichment</Button></CardContent></Card><Card><CardContent><Typography variant="h6">Activate Retro challenge</Typography><Stack direction={{ xs: 'column', md: 'row' }} spacing={1} sx={{ mt: 2 }}><TextField required label="RetroAchievements game ID" value={retroGameId} onChange={(event) => setRetroGameId(event.target.value)} /><TextField fullWidth label="Challenge description (optional)" value={retroDescription} onChange={(event) => setRetroDescription(event.target.value)} /><Button variant="contained" disabled={!retroGameId} onClick={activateChallenge}>Activate</Button></Stack></CardContent></Card><Card><CardContent><Typography variant="h6">Recent durable jobs</Typography><Divider sx={{ my: 1 }} />{jobs.data?.jobs?.slice(0, 10).map((job) => <Typography key={job._id} color="text.secondary">{job.provider} · {job.kind} · {job.status} · attempt {job.attempts}</Typography>)}</CardContent></Card><Card><CardContent><Typography variant="h6">Matches awaiting review</Typography><Divider sx={{ my: 1 }} />{reviews.data?.matches?.length ? reviews.data.matches.map((match) => <Stack key={match.id} spacing={1} sx={{ py: 1.5, borderBottom: 1, borderColor: 'divider' }}><Typography>{match.providerTitle} <Typography component="span" color="text.secondary">· {match.user.username}</Typography></Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><TextField select fullWidth size="small" label="Canonical game" value={selected[match.id] || ''} onChange={(event) => setSelected({ ...selected, [match.id]: event.target.value })}><MenuItem value="" disabled>Select a canonical game</MenuItem>{games.data?.games?.map((game) => <MenuItem key={game.id} value={game.id}>{game.title}</MenuItem>)}</TextField><Button variant="contained" disabled={!selected[match.id]} onClick={() => resolve(match.id)}>Resolve</Button></Stack></Stack>) : <Typography color="text.secondary">No ambiguous matches await review.</Typography>}</CardContent></Card></Stack>;
}
function App() { const fallback = <Box sx={{ minHeight: '30vh', display: 'grid', placeItems: 'center' }}><CircularProgress /></Box>; return <BrowserRouter><Shell><Suspense fallback={fallback}><Routes><Route path="/" element={<Home />} /><Route path="/login" element={<AuthPage />} /><Route path="/signup" element={<AuthPage signup />} /><Route path="/library" element={<Protected><Library /></Protected>} /><Route path="/compare" element={<Protected><Compare /></Protected>} /><Route path="/catalogue" element={<Protected><Catalogue /></Protected>} /><Route path="/retro" element={<Protected><Retro /></Protected>} /><Route path="/admin" element={<Protected><Admin /></Protected>} /><Route path="*" element={<Navigate to="/" />} /></Routes></Suspense></Shell></BrowserRouter>; }
export default App;