import { useCallback, useEffect, useState } from 'react';
import { Alert, Button, Card, CardContent, Chip, CircularProgress, Grid, Stack, TextField, Typography } from '@mui/material';
import { catalogueApi } from '../services/api';

export default function Catalogue() {
  const [query, setQuery] = useState(''); const [games, setGames] = useState([]); const [page, setPage] = useState({ number: 0, size: 60, total: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async (nextPage, replace = false) => { setLoading(true); setError(''); try { const response = await catalogueApi.games(query, nextPage, page.size); setGames((current) => replace ? response.games : [...current, ...response.games]); setPage(response.page); } catch (err) { setError(err.message); } finally { setLoading(false); } }, [page.size, query]);
  useEffect(() => { const timer = setTimeout(() => load(1, true), 200); return () => clearTimeout(timer); }, [load]);
  const shown = games.length; const hasMore = shown < page.total;
  return <Stack spacing={3}><Typography variant="h2">Catalogue</Typography><TextField label="Search canonical games" value={query} onChange={(event) => setQuery(event.target.value)} />{page.total > 0 && <Typography color="text.secondary">Showing {shown} of {page.total} games</Typography>}{error && <Alert severity="error">{error}</Alert>}<Grid container spacing={2}>{games.map((game) => <Grid key={game.id} size={{ xs: 12, sm: 6, lg: 4 }}><Card><CardContent><Typography variant="h6">{game.title}</Typography><Stack direction="row" flexWrap="wrap" gap={.5} sx={{ mt: 1 }}>{game.genres?.map((genre) => <Chip key={genre} size="small" label={genre} />)}</Stack><Typography color="text.secondary" sx={{ mt: 1 }}>{game.summary || 'Metadata is being enriched.'}</Typography></CardContent></Card></Grid>)}</Grid>{loading && <CircularProgress />}{hasMore && !loading && <Button variant="outlined" onClick={() => load(page.number + 1)}>Load more games</Button>}</Stack>;
}