import { useEffect, useState } from 'react';
import { Alert, Autocomplete, Card, CardContent, Chip, CircularProgress, Grid, Stack, TextField, Typography } from '@mui/material';
import { libraryApi } from '../services/api';
import { useLoad } from '../hooks/useLoad';

export default function Compare() {
  const people = useLoad(libraryApi.users, []); const [selected, setSelected] = useState([]); const [result, setResult] = useState(); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!selected.length) { setResult(undefined); return undefined; } let active = true; const timer = setTimeout(async () => { setLoading(true); setError(''); try { const response = await libraryApi.compare(selected.map((person) => person.id)); if (active) setResult(response); } catch (err) { if (active) setError(err.message); } finally { if (active) setLoading(false); } }, 200); return () => { active = false; clearTimeout(timer); }; }, [selected]);
  return <Stack spacing={3}><Typography variant="h2">Compare libraries</Typography><Typography color="text.secondary">Your library is always included. Add players to see games all selected players own.</Typography><Card><CardContent><Autocomplete multiple options={people.data?.users || []} value={selected} onChange={(_, values) => setSelected(values.slice(0, 9))} getOptionLabel={(person) => person.username} isOptionEqualToValue={(option, value) => option.id === value.id} renderInput={(params) => <TextField {...params} label="Search players" placeholder="Type or scroll" />} renderTags={() => null} /><Stack direction="row" flexWrap="wrap" gap={1} sx={{ mt: 2 }}>{selected.map((person) => <Chip key={person.id} label={person.username} color="primary" onDelete={() => setSelected(selected.filter((item) => item.id !== person.id))} />)}</Stack></CardContent></Card>{people.loading || loading ? <CircularProgress /> : null}{error && <Alert severity="error">{error}</Alert>}{selected.length > 0 && result && <><Typography variant="h6">{result.games.length} games shared by everyone selected</Typography>{result.games.length === 0 ? <Typography color="text.secondary">No common games yet.</Typography> : <Grid container spacing={2}>{result.games.map((game) => <Grid key={game.id} size={{ xs: 12, sm: 6, md: 4 }}><Card><CardContent><Typography>{game.title}</Typography><Typography color="text.secondary">Owned by all {result.users.length} players</Typography></CardContent></Card></Grid>)}</Grid>}</>}</Stack>;
}