import { useEffect, useState } from 'react';
import { Alert, Autocomplete, Card, CardContent, Chip, CircularProgress, Grid, Stack, TextField, Typography } from '@mui/material';
import { libraryApi } from '../services/api';
import { useLoad } from '../hooks/useLoad';

export default function Compare() {
  const people = useLoad(libraryApi.users, []); const [selected, setSelected] = useState([]); const [result, setResult] = useState(); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!selected.length) { setResult(undefined); return undefined; } let active = true; const timer = setTimeout(async () => { setLoading(true); setError(''); try { const response = await libraryApi.compare(selected.map((person) => person.id)); if (active) setResult(response); } catch (err) { if (active) setError(err.message); } finally { if (active) setLoading(false); } }, 200); return () => { active = false; clearTimeout(timer); }; }, [selected]);
  return <Stack spacing={3}><Typography variant="h2">Confronta le libbrerie</Typography><Typography color="text.secondary">Scegli da due a dieci persone, pure te se te pare. Vediamo che ve potete giocà senza fa’ riunioni di condominio.</Typography><Card><CardContent><Autocomplete multiple options={people.data?.users || []} value={selected} onChange={(_, values) => setSelected(values.slice(0, 10))} getOptionLabel={(person) => person.username} isOptionEqualToValue={(option, value) => option.id === value.id} renderInput={(params) => <TextField {...params} label="Cerca compari" placeholder="Scrivi o scorri, mica morde" />} renderTags={() => null} /><Stack direction="row" flexWrap="wrap" gap={1} sx={{ mt: 2 }}>{selected.map((person) => <Chip key={person.id} label={person.username} color="primary" onDelete={() => setSelected(selected.filter((item) => item.id !== person.id))} />)}</Stack></CardContent></Card>{people.loading || loading ? <CircularProgress aria-label="Confronto in corso" /> : null}{error && <Alert severity="error">Aò, il confronto s’è messo de traverso: riprova.</Alert>}{selected.length > 0 && result && <><Typography variant="h6">{result.games.length} giochi in comune. Annamo a vede’.</Typography>{result.games.length === 0 ? <Typography color="text.secondary">Niente in comune. Tocca fa’ shopping, che ve devo dì.</Typography> : <Grid container spacing={2}>{result.games.map((game) => <Grid key={game.id} size={{ xs: 12, sm: 6, md: 4 }}><Card component={game.igdbUrl ? 'a' : 'div'} href={game.igdbUrl} target={game.igdbUrl ? '_blank' : undefined} rel={game.igdbUrl ? 'noreferrer' : undefined} className={`game-card${game.igdbUrl ? ' game-card--interactive' : ''}${game.artwork ? ' game-card--cover' : ''}`} sx={{ display: 'block', textDecoration: 'none', backgroundImage: game.artwork ? `url(${JSON.stringify(game.artwork)})` : undefined }}><CardContent><Typography variant="h6" className="game-title-clamp">{game.title}</Typography></CardContent></Card></Grid>)}</Grid>}</>}</Stack>;
}