import { useCallback, useEffect, useState } from 'react';
import { Alert, Button, Card, CardContent, Chip, CircularProgress, Grid, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { useAuth } from '../context/useAuth';
import { libraryApi } from '../services/api';

export default function Library() {
  const { user, refresh } = useAuth(); const [items, setItems] = useState([]); const [page, setPage] = useState({ number: 0, size: 60, total: 0 }); const [loading, setLoading] = useState(true); const [libraryError, setLibraryError] = useState(''); const [steamId, setSteamId] = useState(user?.steamAccount?.steamId || ''); const [provider, setProvider] = useState('gog'); const [file, setFile] = useState(null); const [message, setMessage] = useState(''); const [jobId, setJobId] = useState(null); const [job, setJob] = useState(null);
  const loadLibrary = useCallback(async (nextPage, replace = false) => { setLoading(true); setLibraryError(''); try { const response = await libraryApi.mine(nextPage, page.size); setItems((current) => replace ? response.items : [...current, ...response.items]); setPage(response.page); } catch (error) { setLibraryError(error.message); } finally { setLoading(false); } }, [page.size]);
  useEffect(() => { loadLibrary(1, true); }, [loadLibrary]);
  useEffect(() => { if (!jobId || ['completed', 'completed_with_errors', 'failed'].includes(job?.status)) return undefined; const poll = async () => { try { const result = await libraryApi.job(jobId); setJob(result.job); if (['completed', 'completed_with_errors'].includes(result.job.status)) { await refresh(); await loadLibrary(1, true); } } catch (error) { setMessage(error.message); } }; poll(); const timer = setInterval(poll, 2000); return () => clearInterval(timer); }, [jobId, job?.status, loadLibrary, refresh]);
  const run = async (action) => { try { const result = await action(); if (result?.job) { setJobId(result.job.id); setJob({ ...result.job, status: result.job.status || 'queued' }); setMessage(`Job queued${result.job.gameCount ? ` for ${result.job.gameCount} game(s)` : ''}.`); } else { setMessage('Saved.'); await refresh(); } } catch (error) { setMessage(error.message); } };
  const jobNotice = job && <Alert severity={job.status === 'failed' ? 'error' : job.status === 'completed_with_errors' ? 'warning' : job.status === 'completed' ? 'success' : 'info'}>Job {job.status.replaceAll('_', ' ')}{job.counts?.discovered !== undefined ? ` · ${job.counts.discovered} discovered, ${job.counts.created} created, ${job.counts.updated} updated` : ''}{job.diagnostics?.[0] ? ` · ${job.diagnostics[0].message}` : ''}</Alert>;
  const hasMore = items.length < page.total;
  return <Stack spacing={3}><Typography variant="h2">Your library</Typography>{message && <Alert severity="info">{message}</Alert>}{jobNotice}{libraryError && <Alert severity="error">{libraryError}</Alert>}<Grid container spacing={2}><Grid size={{ xs: 12, lg: 6 }}><Card><CardContent><Typography variant="h6">Steam connection</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1} sx={{ mt: 2 }}><TextField fullWidth label="SteamID64" value={steamId} onChange={(event) => setSteamId(event.target.value)} /><Button variant="outlined" onClick={() => run(() => libraryApi.linkSteam(steamId))}>Save</Button><Button variant="contained" disabled={!user?.steamAccount?.steamId} onClick={() => run(libraryApi.syncSteam)}>Sync</Button></Stack></CardContent></Card></Grid><Grid size={{ xs: 12, lg: 6 }}><Card><CardContent><Typography variant="h6">Import library export</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1} sx={{ mt: 2 }}><TextField select label="Provider" value={provider} onChange={(event) => setProvider(event.target.value)}>{['gog', 'epic', 'amazon'].map((value) => <MenuItem key={value} value={value}>{value.toUpperCase()}</MenuItem>)}</TextField><Button component="label" variant="outlined">{file?.name || 'Choose CSV / JSON'}<input hidden type="file" accept=".csv,.json,text/csv,application/json" onChange={(event) => setFile(event.target.files?.[0])} /></Button><Button variant="contained" disabled={!file} onClick={() => run(() => libraryApi.upload(provider, file))}>Queue</Button></Stack></CardContent></Card></Grid></Grid>{page.total > 0 && <Typography color="text.secondary">Showing {items.length} of {page.total} games</Typography>}<Grid container spacing={2}>{items.map((item) => <Grid key={item.id} size={{ xs: 12, sm: 6, xl: 4 }}><Card><CardContent><Stack direction="row" justifyContent="space-between" spacing={1}><Typography variant="h6">{item.canonicalGame?.title || item.providerTitle}</Typography><Chip size="small" label={item.provider} /></Stack><Typography color="text.secondary">{item.matchStatus.replaceAll('_', ' ')}</Typography></CardContent></Card></Grid>)}</Grid>{loading && <CircularProgress />}{hasMore && !loading && <Button variant="outlined" onClick={() => loadLibrary(page.number + 1)}>Load more games</Button>}</Stack>;
}